services:
  prometheus:
    image: prom/prometheus:latest
    container_name: shopdesk_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - monitoring_network
    depends_on:
      - alertmanager

  grafana:
    image: grafana/grafana:latest
    container_name: shopdesk_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - monitoring_network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: shopdesk_node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring_network

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: shopdesk_blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    restart: unless-stopped
    networks:
      - monitoring_network


  alertmanager:
    image: prom/alertmanager:latest
    container_name: shopdesk_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    networks:
      - monitoring_network

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  monitoring_network:
    driver: bridge
