global:
  scrape_interval: 15s  # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter for system metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['shopdesk_node_exporter:9100']  # Use the container name as the hostname

  # Scrape Blackbox Exporter for HTTP endpoint monitoring
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module for HTTP checks
    static_configs:
      - targets:
          - https://shopdesk.im  # Replace with the URL you want to monitor
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: shopdesk_blackbox:9115  # Use the container name as the hostname