name: CI Pipeline
on: 
  push:
    branches: 
      - main
      - devops 
  pull_request:
    branches: 
      - main
      - devops 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Install Bun globally
      - name: Install Bun
        run: npm install -g bun
      
      # Cache Bun dependencies
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: ~/.bun  # Bun's default cache directory
          key: bun-${{ hashFiles('**/bun.lockb') }}  # Cache based on lockfile
     
      # Install dependencies using Bun
      - name: Install dependencies
        run: bun install
      
      # Run Linting
      - name: Run linting
        run: bun run lint
      
      # Run tests
      - name: Run tests
        run: bun test
